name: gc
channels:
    - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
    - conda-forge
    - defaults
dependencies:
    - python==3.8
    - pip:
        - numpy
        - gym
        - matplotlib
        - ray
        - scipy
        - setproctitle
        - psutil
        - lz4
        - tabulate
        - pandas
        - dataclasses
        - dm-tree
        - tensorboardX
        - torch
        - mlagents==0.27.0